services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dark-patterns-api
    tty: true
    environment:
      SERVICE_NAME: api
      SERVICE_TAGS: dev
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_HOST: ${DB_HOST}
    networks:
      - traefik-public
      - app-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dark-patterns-api.rule=Host(`${APP_HOST}`) && PathPrefix(`/api`)"
      - "traefik.http.routers.dark-patterns-api.entrypoints=web"
      # Forward requests to the correct port on the container
      - "traefik.http.services.dark-patterns-api.loadbalancer.server.port=8000"
      # Middleware to strip the /api prefix before forwarding to the service
      - "traefik.http.routers.dark-patterns-api.middlewares=dark-patterns-strip-api-prefix"
      - "traefik.http.middlewares.dark-patterns-strip-api-prefix.stripprefix.prefixes=/api"
    ports:
      - "${APP_PORT}:8000"
    volumes:
      - ./src:/usr/src/app/dark-patterns-api/src
  db:
    image: mariadb:11.0
    container_name: dark-patterns-db
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    tty: true
    ports:
      - ${DB_PORT}:3306
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
      SERVICE_TAGS: dev
    volumes:
      - database:/var/lib/mysql
    networks:
      - app-network
volumes:
  database:
    driver: local

networks:
  traefik-public:
    external: true
  app-network:
    driver: bridge