version: '3'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api
    tty: true
    environment:
      SERVICE_NAME: api
      SERVICE_TAGS: dev
      DB_NAME: dark-patterns
      DB_USER: dark-patterns
      DB_PASS: dark-patterns
      DB_HOST: dark-patterns-db
    working_dir: /usr/src/app/dark-patterns-api/src
    ports:
      - "8002:8000"
    volumes:
      - ./src:/usr/src/app/dark-patterns-api/src
  db:
    image: mariadb:11.0
    container_name: dark-patterns-db
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    tty: true
    ports:
      - ${DB_PORT-3306}:3306
    environment:
      MYSQL_DATABASE: dark-patterns
      MYSQL_ROOT_PASSWORD: dark-patterns
      MYSQL_USER: dark-patterns
      MYSQL_PASSWORD: dark-patterns
      SERVICE_TAGS: dev
    volumes:
      - database:/var/lib/mysql
volumes:
  database:
    driver: local