version: '3'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api
    tty: true
    environment:
      SERVICE_NAME: api
      SERVICE_TAGS: dev
    working_dir: /usr/src/app
    ports:
      - "8002:8000"
    volumes:
      - ./src:/usr/src/app