# Generated by Django 4.2.7 on 2024-05-26 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0002_websitegroup_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='ux_analyzer_token',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
