# Generated by Django 4.2.7 on 2024-06-04 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0004_remove_website_group_website_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='website',
            name='group',
        ),
        migrations.CreateModel(
            name='WebsiteInGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.SmallIntegerField()),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='websites.websitegroup')),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='websites.website')),
            ],
        ),
    ]
