# Generated by Django 4.2.7 on 2025-03-12 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0005_remove_website_group_websiteingroup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='websiteingroup',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='website_items', to='websites.websitegroup'),
        ),
    ]
