# Generated by Django 4.2.7 on 2024-02-07 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0002_websitegroup_order'),
        ('user_sessions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersession',
            name='website_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_sessions', to='websites.websitegroup'),
        ),
    ]
