# Generated by Django 4.2.7 on 2024-03-15 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_sessions', '0002_usersession_website_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersession',
            name='age',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='usersession',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], default='other', max_length=6),
        ),
        migrations.AddField(
            model_name='usersession',
            name='purchases',
            field=models.CharField(choices=[('none', 'None'), ('1-3', '1-3'), ('4-6', '4-6'), ('>6', '> 6')], default='none', max_length=6),
        ),
    ]
