# Generated by Django 4.2.7 on 2024-05-07 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_sessions', '0005_alter_usersession_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersession',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254),
            preserve_default=False,
        ),
    ]
