# Generated by Django 4.2.7 on 2023-12-29 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website', models.CharField(max_length=255)),
                ('dark', models.BooleanField(default=False)),
                ('questionnaire', models.JSONField()),
                ('date', models.DateTimeField(auto_now=True)),
                ('sample_data', models.JSONField()),
            ],
        ),
    ]
