# Generated by Django 4.2.7 on 2023-12-29 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='sample_data',
            field=models.JSONField(default={}),
        ),
    ]
