# Generated by Django 4.2.7 on 2024-03-15 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0005_sample_time_alter_sample_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sample',
            name='time',
        ),
        migrations.AddField(
            model_name='sample',
            name='end',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='sample',
            name='start',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='sample',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
