apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: api
  name: api
spec:
  replicas: 1
  selector:
    matchLabels:
     app: api        
  template:
    metadata:            
      labels:
        app: api        
    spec:
      containers:
        - name: api
          image: jcgardey/dark-patterns:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
              protocol: TCP  