apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: dark-patterns-api
  name: dark-patterns-api
spec:
  replicas: 1
  selector:
    matchLabels:
     app: dark-patterns-api        
  template:
    metadata:            
      labels:
        app: dark-patterns-api        
    spec:
      containers:
        - name: dark-patterns-api
          image: jcgardey/dark-patterns:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
              protocol: TCP
          env:
            # Define the environment variable
            - name: DB_NAME 
              value: "darkpatterns"  
            - name: DB_PASS
              value: "dark-patterns"  
            - name: DB_USER
              value: "dark-patterns"  
            - name: DB_HOST
              value: "dark-patterns-db"  