kind: Service
apiVersion: v1
metadata:  
  name: dark-patterns-api
spec:
  ports:    
    - name: dark-patterns-api
      protocol: TCP
      port: 8000
      targetPort: 8000    
  selector:
    app: dark-patterns-api