apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: dark-patterns-api
spec:
  rules:
    - host: dark-patterns-api.okd.lifia.info.unlp.edu.ar
      http:
        paths:
          - path: /
            backend:
              serviceName: dark-patterns-api
              servicePort: 8000